version: "3.9"
services:
  
  # DRS

  # Create DRS Database
  drs-migrate:
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_1_drs_migrate
    volumes:
      - "./resources/drs/db:/db"
    command: database create-tables -d jdbc:sqlite:/db/drs.db drs@v0.3.1

  # Add default data to DRS Database
  drs-dataset:
    depends_on:
      - drs-migrate
    image: ga4gh/ga4gh-starter-kit-utils:0.1.2
    container_name: part_1_drs_dataset
    volumes:
      - "./resources/drs/db:/db"
    command: database add-test-dataset -d jdbc:sqlite:/db/drs.db drs@v0.3.1

  # DRS Starter Kit
  drs:
    depends_on:
      - drs-migrate
      - drs-dataset
    image: ga4gh/ga4gh-starter-kit-drs:0.3.1
    hostname: drs.starterkit.federatedgenomics.org
    container_name: part_1_drs
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./resources/drs/config:/config"
      - "./resources/drs/db:/db"
    command: -c /config/config.yml